### ISSUE TITLE
DB Migration is failing

### ISSUE THREAD

**Issue by raghu999** [madedotcom/portus-pie-provisioner#2]
Hi i am trying to use your Code to Launch Portus in production I have configured prod_portus.env accordingly .`PORTUS_PRODUCTION_HOST=db` is not working throwing an error unable to connect to db , Then i have changed it to `PORTUS_PRODUCTION_HOST=portus-db` , now i see the below error.

When running with `PORTUS_PRODUCTION_HOST=db`
```
#<Mysql2::Error: Unknown MySQL server host 'db' (22)>
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "host"=>"db", "username"=>"root", "password"=>"portus", "database"=>"portus"}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
Error running migration! Please review database configuration
rake aborted!
Mysql2::Error: Unknown MySQL server host 'db' (22)
```

When running with `PORTUS_PRODUCTION_HOST=portus-db`

```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "host"=>"portus-db", "username"=>"root", "password"=>"portus", "database"=>"portus"}
Error running migration! Please review database configuration
rake aborted!
Mysql2::Error: Access denied for user 'root'@'172.17.0.7' (using password: YES)

Tasks: TOP => db:migrate:reset => db:migrate
(See full trace by running task with --trace)
Access denied for user 'root'@'172.17.0.7' (using password: YES)Please provide the root password for your MySQL installation

> failed, will retry
```

**Comment by raghu999** [comment]
Can Confirm that changing  PORTUS_PRODUCTION_HOST=portus-db in prod_portus.env solved my issue Thanks

**Comment by egidijus** [comment]
Thank you @raghu999 !
That is great to hear.
Any feedback is welcome.

**Comment by raghu999** [comment]
`docker-compose run -d portus-migrate` works fine for me but the Script 01_start_config.sh is breaking at migration.

**Comment by egidijus** [comment]
@raghu999 
I have updated the script to call the migration container, instead of trying to do it the other way.
please try again with updated code.

**Comment by egidijus** [comment]
Can this issue be closed ?
