### ISSUE TITLE
Portus UI Reports Something Wrong

### ISSUE THREAD

**Issue by raghu999** [madedotcom/portus-pie-provisioner#3]
Hi @egidijus i was able to successfully Launch All the containers and When visiting the UI `domain.example:3000` SSL error is being shown on the WEB UI.

<img width="766" alt="screen shot 2016-03-16 at 1 23 46 pm" src="https://cloud.githubusercontent.com/assets/12721392/13822182/05873f68-eb7b-11e5-8414-11a05d76b372.png">

**Comment by egidijus** [comment]
You should have an nginx container listening on port `80` and `443`.
That container should proxy all portus requests.

Also do be aware that this project assumes you have either wildcard or multidomain certificate.
so portus and docker registry will be proxied by nginx under different subdomains.

**Comment by raghu999** [comment]
Thanks @egidijus Got It

**Comment by egidijus** [comment]
Please let me know if this is solved.

**Comment by raghu999** [comment]
I Have requested new SANS certs with Subdomains will Update once i do the entire Setup

**Comment by egidijus** [comment]
I have updated the script to be more informative on what the final state is, so you know what port/address you should be going to.

@raghu999 have you tried Let's encrypt ?
this guide looks like it might help you create multidomain certs.
https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-certificates-for-multiple-apache-virtual-hosts-on-ubuntu-14-04
